import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "../globals.css";

export const sarabunFont = Sarabun ( {
  weight: ["400", "500", "700"],
  subsets: ["thai"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
    >
      <body className={sarabunFont.className}>
      <main className="flex min-h-screen items-center justify-center p-6">
         {children}
      </main>
      </body>
    </html>
  );
}