import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import Navbar from "@/components/navbar";
import { Html } from "next/document";

export const promptFont = Prompt ( {
  weight: ["400", "500", "700"],
  subsets: ["thai"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="th" suppressHydrationWarning>
      <body className={promptFont.className}>
        <Navbar />

        <nav className="flex gap-4 border-b p-4">
          <Link href="/">Home</Link>
          <Link href="/about">About Us</Link>
          <Link href="/sign-in">Login</Link>
          <Link href="/sign-up">Register</Link>
        </nav>
        
        {children}
      </body>
    </html>
  );
}

